apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: geo-nap
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - cost-estimator.yaml
  - ai-extraction.yaml
  - pricing-sync-worker.yaml
  - frontend.yaml
  - ingress.yaml
