apiVersion: v1
kind: Secret
metadata:
  name: geo-nap-secrets
  namespace: geo-nap
type: Opaque
stringData:
  DATABASE_URL: "postgresql://geo_nap:geo_nap@postgres.geo-nap.svc.cluster.local:5432/geo_nap"
  JWT_SECRET: "replace-with-strong-32-plus-char-secret"
  OPENAI_API_KEY: ""
  PERPLEXITY_API_KEY: ""
  GCP_SERVICE_ACCOUNT_JSON: ""
